In [1]:
matrix_1 = [[1, 2],[3, 4]]
for i in range(len(matrix_1)):
    for j in range(len(matrix_1)):
        matrix_1[i][j] = matrix_1[i][j] + 1
print(matrix_1)

[[2, 3], [4, 5]]


In [2]:
import numpy as np
matrix_1 = [[1, 2],[3, 4]]
matrix_1 = np.array(matrix_1) + 1
print(matrix_1)

[[2 3]
 [4 5]]


In [3]:
x = np.uint(32)
print(x.dtype)

uint32


In [4]:
x = np.float32([1, 2, 3, 4])
print(x.dtype)

float32


In [5]:
x

array([1., 2., 3., 4.], dtype=float32)

In [6]:
x = np.array([1, 2, 3, 4], dtype=np.float32)
print(x.dtype)

float32


In [7]:
x = np.int32(x)
print(x.dtype)
np.issubdtype(x.dtype, np.int32)

int32


True

In [8]:
x = np.array(1)
print(x.shape)
print(x.ndim)
print(x.size)
print(x)

()
0
1
1


In [9]:
x = np.array([1, 2])
print(x.shape)
print(x.ndim)
print(x.size)
print(x)

(2,)
1
2
[1 2]


In [10]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x.shape)
print(x.ndim)
print(x.size)
print(x)

(2, 3)
2
6
[[1 2 3]
 [4 5 6]]


In [11]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
x = np.arange(10.0)
print(x)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [13]:
x = np.arange(1, 10, 2)
print(x)

[1 3 5 7 9]


In [14]:
x = np.arange(1, 10, 0.5)
print(x)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [15]:
x = np.arange(10, 1, -0.5)
print(x)

[10.   9.5  9.   8.5  8.   7.5  7.   6.5  6.   5.5  5.   4.5  4.   3.5
  3.   2.5  2.   1.5]


In [16]:
x = np.linspace(1, 20, 5)
print(x)

[ 1.    5.75 10.5  15.25 20.  ]


In [17]:
x = np.linspace(1, 20, 10, endpoint=False)
print(x)

[ 1.   2.9  4.8  6.7  8.6 10.5 12.4 14.3 16.2 18.1]


In [18]:
x = np.arange(9).reshape(3, 3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [19]:
x = np.arange(24).reshape(2, 3, 4)
print(x)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [20]:
x = np.arange(16).reshape(2, 2, 2, 2)
print(x)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


In [21]:
x = np.array([[1,2],[3,4],[5,6]])
print(x)
print(x.reshape(2,3))

[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


In [22]:
x = np.arange(10, 1, -0.5)
print(x)

[10.   9.5  9.   8.5  8.   7.5  7.   6.5  6.   5.5  5.   4.5  4.   3.5
  3.   2.5  2.   1.5]


In [23]:
# 1차원 슬라이싱
x = np.arange(20)
print(x[1:3])

[1 2]


In [24]:
x[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [25]:
x[-2:]

array([18, 19])

In [26]:
# 2차원 슬라이싱
x = np.arange(20).reshape(4,5)
print(x)
print(x[1:3])
print(x[1:3, 1:3])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 6  7]
 [11 12]]


In [27]:
# 3차원 슬라이싱
x = np.arange(30).reshape(2,5,3)
print(x)
print(x[:,3:5,1])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]
[[10 13]
 [25 28]]


In [28]:
a = np.arange(20).reshape(4, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [29]:
# indexing
print(a[1][1])
print(a[1,1])
print(a[[1,1],[1,2]])

6
6
[6 7]


In [30]:
# boolean indexing
print(a > 3)
print(a[a > 3])
print(a[a == 1])
print(a[~(a == 1)])
print(a[(a > 3)&(a < 8)])

[[False False False False  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[1]
[ 0  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[4 5 6 7]


In [31]:
np.random.rand(5,5)

array([[0.65976489, 0.5802    , 0.39618712, 0.36920536, 0.96543582],
       [0.40909296, 0.90851749, 0.03155269, 0.4267314 , 0.92314224],
       [0.88985028, 0.17823477, 0.22177949, 0.14897434, 0.93323678],
       [0.99335122, 0.87877517, 0.17589929, 0.72628089, 0.88927867],
       [0.37654527, 0.91387873, 0.56186113, 0.97344784, 0.24226745]])

In [32]:
np.random.randint(1, 10)

5

In [33]:
np.random.randint(1, 10, size=(5))

array([5, 7, 2, 3, 1])

In [34]:
np.random.randint(1, 10, size=(5, 5))

array([[6, 7, 9, 4, 4],
       [7, 9, 1, 8, 4],
       [2, 5, 2, 4, 3],
       [3, 1, 5, 9, 6],
       [8, 8, 9, 4, 4]])

In [35]:
np.random.choice(100, size=(3, 4))
x = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.random.choice(x, size=(2, 2)) # 분석하는 과정에서 쓰이지 않음

array([[3, 2],
       [4, 2]])

In [36]:
np.ones([5, 5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [37]:
np.zeros([5, 5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [38]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [39]:
x = np.arange(1, 4)
y = np.arange(4, 7)
np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

In [40]:
x = np.arange(10).reshape(2, 5)
y = np.arange(10, 20).reshape(2, 5)
np.concatenate([x, y])
np.concatenate([x, y], axis=1)

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [41]:
x = np.arange(12)
np.split(x, 4)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [42]:
x = np.arange(16).reshape(4, 4)
np.split(x, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [43]:
x = np.arange(16).reshape(4, 4)
np.split(x, 2, axis=1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [44]:
x = np.array([1,2,3])
x + 1

array([2, 3, 4])

In [45]:
x = np.arange(1, 10).reshape(3, 3)
y = np.arange(1, 4)
x + y

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [46]:
x = np.array([10, 20, 30]).reshape(3, 1)
y = np.arange(1, 4)
x + y

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [47]:
x = np.arange(4).reshape(2, 2)
y = np.arange(4).reshape(2, 2)
print(x.dot(y)) # 행렬곱
print(np.transpose(x)) # 전치행렬
print(np.linalg.inv(x)) # 역행렬
print(np.linalg.det(x)) # 행렬식
print(np.mean(x)) # 평균
print(np.median(x)) # 중앙값
print(np.std(x)) # 표준편차
print(np.var(x)) # 분산
print(np.sum(x)) # 합
print(np.sum(x, axis=1)) # 합,축변경

[[ 2  3]
 [ 6 11]]
[[0 2]
 [1 3]]
[[-1.5  0.5]
 [ 1.   0. ]]
-2.0
1.5
1.5
1.118033988749895
1.25
6
[1 5]


In [48]:
print(np.cumsum(x)) # 누적합
print(np.cumprod(x)) # 누적곱
print(np.min(x)) # 최소값
print(np.argmin(x)) # 최소값 위치
print(np.argmax(x)) # 최대값 위치
print(np.any(x > 4)) # 하나라도 참이어야 참
print(np.all(x > 4)) # 모든 요소가 참이어야 참
print(np.where(x > 4)) # 조건에 맞는위치
print(np.where(x > 4, x, -100)) # 조건, True 일경우, False 일경우

[0 1 3 6]
[0 0 0 0]
0
0
3
False
False
(array([], dtype=int64), array([], dtype=int64))
[[-100 -100]
 [-100 -100]]


## 실습 01

In [49]:
x = np.arange(1, 10).reshape(3, 3)
y = np.arange(10, 100, 10).reshape(3, 3)
print(x + y)
print(np.dot(x, y))

[[11 22 33]
 [44 55 66]
 [77 88 99]]
[[ 300  360  420]
 [ 660  810  960]
 [1020 1260 1500]]


## 실습 02

In [50]:
x = np.linspace(1, 20, 30)
print(x + 10)

[11.         11.65517241 12.31034483 12.96551724 13.62068966 14.27586207
 14.93103448 15.5862069  16.24137931 16.89655172 17.55172414 18.20689655
 18.86206897 19.51724138 20.17241379 20.82758621 21.48275862 22.13793103
 22.79310345 23.44827586 24.10344828 24.75862069 25.4137931  26.06896552
 26.72413793 27.37931034 28.03448276 28.68965517 29.34482759 30.        ]


## 실습 03

In [51]:
x = np.random.randint(1, 100, size=(2, 10, 10))
print(x)

[[[77 24 68  8 78 49 47  3 41 53]
  [16 44 32 59 90 96  1 17  4 57]
  [64 83 84 25 99  8 25 42 15 55]
  [ 6 81 94 38 19 44 84 99 63 27]
  [82 58 23 85 44 34 58 44 36 95]
  [47 24 72 15  6 60 46 36 57 60]
  [48 78 50 24 22 32 33 86  2 46]
  [13 95  5 73 47 56 10 15 66 51]
  [56 47 42 29 55 33  2 82 28 99]
  [39 72 69 38 56 96 93 77 77 41]]

 [[26 50 10 91 34 73 27 67 61 57]
  [36 39 66 57 15 62 82 65 90 22]
  [46  9 71 83 77 58 85  9  6 85]
  [37  8 33 45 44  9  5 15 56 73]
  [19 83 27  7 68 93 48 47  3 94]
  [39 17 72  8 28 18 89  5 89 98]
  [56 10 61 11 58 12 65 82 23 69]
  [63 20 11 53  4 20 39 45  5 20]
  [11 15 35 33 15  8 57 65 57  7]
  [23 80 45 89 56  5 11 67 34 54]]]


In [52]:
y = np.where(x >= 50, 1, 2)
print(y)

[[[1 2 1 2 1 2 2 2 2 1]
  [2 2 2 1 1 1 2 2 2 1]
  [1 1 1 2 1 2 2 2 2 1]
  [2 1 1 2 2 2 1 1 1 2]
  [1 1 2 1 2 2 1 2 2 1]
  [2 2 1 2 2 1 2 2 1 1]
  [2 1 1 2 2 2 2 1 2 2]
  [2 1 2 1 2 1 2 2 1 1]
  [1 2 2 2 1 2 2 1 2 1]
  [2 1 1 2 1 1 1 1 1 2]]

 [[2 1 2 1 2 1 2 1 1 1]
  [2 2 1 1 2 1 1 1 1 2]
  [2 2 1 1 1 1 1 2 2 1]
  [2 2 2 2 2 2 2 2 1 1]
  [2 1 2 2 1 1 2 2 2 1]
  [2 2 1 2 2 2 1 2 1 1]
  [1 2 1 2 1 2 1 1 2 1]
  [1 2 2 1 2 2 2 2 2 2]
  [2 2 2 2 2 2 1 1 1 2]
  [2 1 2 1 1 2 2 1 2 1]]]


In [53]:
np.split(y[1][5:], 2, axis = 1)[1]

array([[2, 1, 2, 1, 1],
       [2, 1, 1, 2, 1],
       [2, 2, 2, 2, 2],
       [2, 1, 1, 1, 2],
       [2, 2, 1, 2, 1]])